feat: ✨ Avila Custom Theme
Avila-Tek/flutter_common_lib pull request #10
Opened 2024-02-09 19:22 UTC by ortegadn

Definition of the Avila Custom Theme. 
Here all ThemeExtensions are defined and then obtained and declared in the ThemeData of each application

2024-02-16 22:12 UTC, andrespd99 requested changes

2024-02-16 22:12 UTC, andrespd99 commented on packages/avilatek_ui/lib/src/ui/avila_custom_theme.dart
> +  const AvilaCustomTheme({
Hay que hacer todos los estilos opcionales

2024-02-18 19:33 UTC, lesanpi requested changes
Lo que comento Andrew

2024-02-19 14:20 UTC, CADSV reviewed
Lo que comentó Luisao de lo que comentó Andrew xd

2024-02-23 19:45 UTC, andrespd99 commented
> Lo que comentó Luisao de lo que comentó Andrew xd

JAJAJA

2024-02-23 19:46 UTC, merged