Developed By Widget FLC-007
Avila-Tek/flutter_common_lib pull request #11
Opened 2024-02-14 23:11 UTC by Vizten18

2024-02-15 17:50 UTC, nathva requested changes
Te dejé unos comentarios pequeños, más que nada asociados a los colores y cómo se manejan, pero todo se ve bastante bien:).

2024-02-15 17:50 UTC, nathva commented on packages/avilatek_ui/lib/src/widgets/developed_by.dart
> +  }
También deberías poder cambiar el color al contorno del logo! Funciona de manera similar al flat.

2024-02-15 17:50 UTC, nathva commented on packages/avilatek_ui/lib/src/widgets/developed_by.dart
> +            color: color ?? Colors.black,
Si estás usando la version primaryWhite, el texto también debería ser blanco, para permitir que sea legible. Si no, el texto va a ser incompatible y alguno no se va a ver bien.

2024-02-15 17:50 UTC, nathva commented on example/lib/pages/developed_by_logo/developed_by_logo_example.dart
> +          ),
Podrías rodear este ejemplo en un container negro para que sea más visible! 

```dart 
Container(
            color: Colors.black,
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                const Text('Primary White (Modified Size)'),
                const Spacer(),
                DevelopedByLogo(size: 20).primaryWhite(),
                const Spacer(),
              ],
            ),
          ),
```

2024-02-16 22:18 UTC, andrespd99 requested changes

2024-02-16 22:18 UTC, andrespd99 commented on packages/avilatek_ui/lib/src/widgets/developed_by.dart
> +        Text(
El tamaño del texto debería ser proporcional al size. Puede ser una formula sencilla, algo asi como `textSize: size - x`, siendo X algun valor que veas que respete las proporciones del logo con el texto.

2024-02-16 22:18 UTC, andrespd99 commented on packages/avilatek_ui/lib/src/widgets/developed_by.dart
> +            color: color ?? Colors.black,
Totalmente. @Vizten18 creo que puedes pasarle el color blanco por parámetro a la funcion _buildLogo del constructor .primaryWhite

2024-02-19 14:33 UTC, CADSV approved these changes
Brutal Vicent!

2024-02-19 15:19 UTC, andrespd99 approved these changes

2024-02-19 15:19 UTC, merged