Feat: ✨ Verify and Send code bloc
Avila-Tek/flutter_common_lib pull request #14
Opened 2024-02-20 16:48 UTC by CADSV

- Feat: ✨ VerifyCodeBloc.
- Feat: ✨ SendCodeBloc.
- Feat: ✨ Example page.

2024-02-20 18:29 UTC, lesanpi requested changes

2024-02-20 18:29 UTC, lesanpi commented on packages/avilatek_bloc/lib/src/send_code/send_code_bloc.dart
En la practica real, para verificar el código, se envía el Email a los queries. Por lo que hace falta meter el campo email en bloc!

2024-02-20 18:35 UTC, lesanpi requested changes

2024-02-20 18:35 UTC, lesanpi commented on packages/avilatek_bloc/lib/src/verify_code/verify_code_bloc.dart
> +abstract class VerifyCodeBloc extends Bloc<VerifyCodeEvent, VerifyCodeState> {
En los casos reales, se necesitan el email del usuario. Agrégalo como un campo del Bloc (NO al state)

2024-02-20 18:38 UTC, lesanpi requested changes

2024-02-20 18:38 UTC, lesanpi commented on packages/avilatek_bloc/lib/src/send_code/send_code_state.dart
Donde guardas el String code?
Que es el que cambia cuando escribes con el teclado

2024-02-20 18:38 UTC, lesanpi commented on packages/avilatek_bloc/lib/src/send_code/send_code_event.dart
Falta el evento que haga el SendCodeInputChanged o algo por el estilo, que le mandes el String del código y lo guarde en state

2024-02-20 18:42 UTC, CADSV commented on packages/avilatek_bloc/lib/src/send_code/send_code_bloc.dart
Esto yo lo conversé con Andrew y me dijo que él quiere que el bloc sea agnóstico a cualquier tipo de verificación, entonces no sé si agregarle un email sería atarlo a una implementación puntual

2024-02-20 18:44 UTC, CADSV commented on packages/avilatek_bloc/lib/src/send_code/send_code_state.dart
En el state de la implementación, que es el verify cubit. O lo guardo directamente en el VerifyCodeState? No puede ser en el send porque ese bloc únicamente se encarga de enviar el código al usuario a través del medio establecido en la implementación

2024-02-20 18:44 UTC, CADSV commented on packages/avilatek_bloc/lib/src/send_code/send_code_bloc.dart
> +abstract class SendCodeBloc extends Bloc<SendCodeEvent, SendCodeState> {
Cierto, veo que me faltó en algunos sitios, voy

2024-02-20 18:44 UTC, CADSV commented on packages/avilatek_bloc/lib/src/send_code/send_code_event.dart
Pero no debería ser en el VerifyCodeState?

2024-02-20 20:08 UTC, CADSV commented on packages/avilatek_bloc/lib/src/send_code/send_code_state.dart
Listo

2024-02-20 20:08 UTC, CADSV commented on packages/avilatek_bloc/lib/src/send_code/send_code_event.dart
Listo

2024-02-20 20:14 UTC, CADSV commented on packages/avilatek_bloc/lib/src/send_code/send_code_bloc.dart
> +abstract class SendCodeBloc extends Bloc<SendCodeEvent, SendCodeState> {
Listooo

2024-02-21 02:12 UTC, CADSV commented on packages/avilatek_bloc/lib/src/send_code/send_code_event.dart
Listoo

2024-02-21 03:09 UTC, lesanpi requested changes

2024-02-21 03:09 UTC, lesanpi commented on example/lib/pages/verify_password/verify_password_example_page.dart
> +                      .add(const SendCodePressedEvent())
Considero esto como otro evento distinto al SendCodePressedEvent.
Este seria ResendCodePressedEvent.

2024-02-21 03:09 UTC, lesanpi commented on packages/avilatek_bloc/lib/src/verify_code/verify_code_bloc.dart
> +abstract class VerifyCodeBloc extends Bloc<VerifyCodeEvent, VerifyCodeState> {
Siento que este Bloc requiere de que se inicie con un campo requerido que sea el input que ya previamente fue definido en el SendCodeBloc.
Como te digo el caso de uso es este:
1. El usuario pone se email o telefono, lo manda por el bloc de sendCodeBloc.
2. El usuario esta en el VerifyCodeBloc, se supone que debes decirle el teléfono o email que estas verificando. "Verificame el código que le enviaste a este email"
3. En el caso de reenviar el código. "Ya te indique el email, solo quiero que lo reenvíes al mismo email"

2024-02-21 03:09 UTC, lesanpi commented on example/lib/pages/verify_password/verify_password_example_page.dart
> +                      .add(const SendCodePressedEvent())
Este si le tienes que pasar algo como parámetros "email al que estoy verificando, reenvía", "teléfono que quiero que le reenvíes el código"

2024-02-21 14:24 UTC, CADSV commented on packages/avilatek_bloc/lib/src/send_code/send_code_bloc.dart
> +
Listo

2024-02-21 14:25 UTC, CADSV commented on packages/avilatek_bloc/lib/src/verify_code/verify_code_event.dart
> +class VerifyCodePressedEvent extends VerifyCodeEvent {
Mmm es verdad

2024-02-21 14:31 UTC, CADSV commented on packages/avilatek_bloc/lib/src/send_code/send_code_state.dart
> +  String get input => _input;
Listooo

2024-02-21 14:46 UTC, CADSV commented on example/lib/pages/verify_password/enter_input_sender_example_page.dart
> +                Navigator.push(
Listo

2024-02-21 18:12 UTC, CADSV commented on packages/avilatek_bloc/lib/src/verify_code/verify_code_bloc.dart
> +abstract class VerifyCodeBloc extends Bloc<VerifyCodeEvent, VerifyCodeState> {
Listo

2024-02-21 18:13 UTC, CADSV commented on example/lib/pages/verify_password/verify_password_example_page.dart
> +class ResendTimer extends StatelessWidget {
Vamos a abrir un issue sobre eso

2024-03-18 15:31 UTC, closed without merging

2024-03-18 15:31 UTC, andrespd99 commented
Se cierra el PR dado que el concepto del bloc no está totalmente claro y puede generar la implementación puede generar mas overhead que beneficios.