FLC-009 - CustomLoadingIndicator
Avila-Tek/flutter_common_lib pull request #15
Opened 2024-02-21 22:35 UTC by Vizten18

2024-02-23 20:03 UTC, andrespd99 requested changes

2024-02-23 20:03 UTC, andrespd99 commented on packages/avilatek_ui/lib/src/widgets/custom_loading_indicator.dart
Siento que el parámetro style puede ser un tanto confuso, ya que solo aplica si el child es `null`...

Considero mejor eliminar ese parámetro. En caso de que el dev quiera cambiar el estilo del indicador default, que inyecte el widget y modifique su style en el theme del CustomLoadingIndicator

2024-02-23 20:03 UTC, andrespd99 commented on packages/avilatek_ui/lib/src/widgets/custom_loading_indicator.dart
> +    return child ?? AdaptiveLoaderIndicators(style: style);
Falta evaluar si el ThemeData tiene child antes de caer en el fallback

2024-02-23 20:03 UTC, andrespd99 commented on packages/avilatek_ui/lib/src/widgets/custom_loading_indicator.dart
> +    return child ?? AdaptiveLoaderIndicators(style: style);
La clase AdaptiveLoaderIndicators no es necesaria. Puedes usar CircularProgressIndicator.adaptive() que hace lo mismo

2024-02-26 14:12 UTC, cadsvpt approved these changes

2024-02-26 14:13 UTC, CADSV approved these changes

2024-03-05 16:53 UTC, merged