feat: ✨ Custom Tag
Avila-Tek/flutter_common_lib pull request #18
Opened 2024-03-11 13:42 UTC by ortegadn

FCL-010
Se agregó el widget Custom Tag a la libreria, el cual recibe como child un widget (por lo general tipo Text) para mostrar.
Se colocaron constructores por defecto para unos tags especificos de color rojo, amarillo, verde, gris y el color primario de la app.

2024-03-11 13:58 UTC, lesanpi requested changes

2024-03-11 13:58 UTC, lesanpi commented on packages/avilatek_ui/lib/src/widgets/custom_tags.dart
> +        style?.backgroundColor ?? primaryColor.withOpacity(0.3);
No se si debería ser el primary con opacidad, sino mas bien un shade100 o shade50. Por que me ha pasado que en los dark mode se vuelve un descontrol cuando uso opacity, también cuando es fondos grises etc...

2024-03-11 13:58 UTC, lesanpi commented on packages/avilatek_ui/lib/src/ui/avila_custom_theme.dart
> +        customTagStyle ?? const CustomTagStyle(),
Creo que seria mas util, si creamos un CustomTagTheme, que tenga 3 campos: SuccessTagStyle, WarningTagStyle, FailureTagStyle. Incluso podrias poner uno normal que sea style, que sea el por defecto (seria como el cuarto campo). De esta forma ya se define en toda la aplicación como serian los tags success, los tags de warning y los de error.

2024-03-11 13:58 UTC, lesanpi commented on packages/avilatek_ui/lib/src/widgets/custom_tags.dart
> +  factory CustomTag.yellow(
Podrias hacer la idea de los theme que te comente anteriormente, para que este factory sea mas customizable a través del theme

2024-03-18 15:29 UTC, andrespd99 requested changes

2024-03-18 15:29 UTC, andrespd99 commented on packages/avilatek_ui/lib/src/widgets/custom_tags.dart
> +  factory CustomTag.yellow(
Me gusta la idea, e incluso podemos usar el mismo CustomTagStyle para cada variante y así no es necesario crear una clase por variante.

Lo que se me ocurre es crear una clase `CustomTagThemeData` que tenga los atributos (opcionales) `primaryStyle`, `greenStyle`, `yellowStyle`, `redStyle`, etc; todos de tipo `CustomTagStyle`. De esa forma, aprovechas tener todas las variantes a la mano accesibles a través del context, y no requiere tener una clase para el estilo de cada variante. Puedes ponerle por defecto valores arbitrarios. Por ejemplo, el `redStyle` tendrá colores rojos por defecto. 

Otra cosa, yo cambiaría primaryOne por `primary`, y agregaría un `secondary` ya que es lo más común.

Siguiendo esa idea, una implementación real debería quedar algo así como:

`CustomTag.primary(context, ...)`

2024-03-18 15:30 UTC, andrespd99 commented
El Widget está brutal! Solo cambiaría esos detalles que te comenté sobre los estilos de las variantes y listo.

2025-01-15 18:42 UTC, andrespd99 approved these changes

2025-01-15 18:44 UTC, merged