feat: ✨ Widget with title
Avila-Tek/flutter_common_lib pull request #3
Opened 2024-01-29 14:43 UTC by ortegadn

FCL-004

WidgetWithTitle added to flutter common lib.

This widget acts as a content section in an app, which can have a title, a widget or set of widgets (which generally displays the content), and an optional footer.

As for customization, you must define a title in the form of a String or in the form of a widget if you want a more specific one for the section, a widget as a child and an optional footer Widget.

Additionally, a theme was defined for this widget where you can customize the space between the title and the child or the footer and the child, in addition to the TextStyle of the title and the footer.

2024-01-29 19:39 UTC, CADSV reviewed
Me gustó, aunque admito que tengo algunas dudas con el theme porque nunca he hecho uno, sobre todo la parte de los lerps y eso, así que investigaré un poco al respecto para poder implementar el theme de mi widget

2024-01-29 19:39 UTC, CADSV approved these changes

2024-01-30 00:37 UTC, lesanpi approved these changes
Muy bien todo. Siento que la nomenclatura podría mejorar, hay un widget de flutter llamado "Title", pero tampoco me convence "WidgetWithTitle"
Sugiero:
* TitleWidget
* TitleWrapper
* TitleChild
* TitleImproved
* TitleSection

2024-01-30 15:20 UTC, andrespd99 requested changes

2024-01-30 15:20 UTC, andrespd99 commented on packages/avilatek_ui/lib/src/ui/avila_theme_data.dart
> +    fieldWithTitleTheme ??= WidgetWithTitleThemeData(
Los atributos defaults definelos directamente en la clase del widget.

Ve como lo hacen en cualquiera de los widgets de material (ie. [TextButton](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/text_button.dart))

2024-01-30 15:20 UTC, andrespd99 commented on packages/avilatek_ui/lib/src/ui/widget_with_title/widget_with_title_theme.dart
Luego de descubrir ThemeExtension, queda claro que es exactamente lo que hay que hacer acá.

Extiende esta clase de `ThemeExtension<WidgetWithTitleThemeData>` e implementa sus funciones obligatorias.

2024-01-30 15:20 UTC, andrespd99 commented on packages/avilatek_ui/lib/src/ui/avila_theme_data.dart
Es posible que con los ThemeExtensions cambie por completo el modelo de AvilaThemeData, o se elimine por completo.

Aunque yo lo dejaría mínimo como proveedor de la lista de extensiones de nuestros custom themes

2024-01-30 15:26 UTC, andrespd99 commented
Mergea con dev

2024-02-01 17:40 UTC, andrespd99 approved these changes

2024-02-01 17:40 UTC, merged