feat: 🎉 Adaptive Dialog
Avila-Tek/flutter_common_lib pull request #4
Opened 2024-01-29 23:21 UTC by Vizten18

Adaptive dialog integrated, adaptive dialog with input created

2024-01-30 15:55 UTC, andrespd99 requested changes

2024-01-30 15:55 UTC, andrespd99 commented on packages/avilatek_ui/lib/src/widgets/adaptive_dialog.dart
Agregale a `AdaptiveDialogAction` la propiedad `style` de tipo `AdaptiveDialogActionStyle` (vas a tener que crear esa clase).

Ese style va a sobrescribir todos los estilos que estén por encima (a nivel del AdaptiveDialog.actionsStyle, o el theme en el context).

2024-01-30 15:55 UTC, andrespd99 commented on packages/avilatek_ui/lib/src/ui/adaptive_dialog/adaptive_dialog_theme.dart
Extiende esta clase de `ThemeExtensions<AdaptiveDialogThemeData>`.

2024-02-01 19:50 UTC, CADSV approved these changes

2024-02-06 15:03 UTC, andrespd99 requested changes

2024-02-06 15:03 UTC, andrespd99 commented on packages/avilatek_ui/lib/src/ui/adaptive_dialog/adaptive_dialog_theme.dart
> +  });
cupertinoTextStyle
materialButtonStyle

2024-02-07 16:38 UTC, andrespd99 requested changes

2024-02-15 17:06 UTC, merged