Feat: ✨Selector Sheet Widget
Avila-Tek/flutter_common_lib pull request #8
Opened 2024-02-06 14:11 UTC by CADSV

- Feat: ✨ Done selector sheet widget.
- Feat: ✨ Added selector sheet theme.
- Feat: ✨ Added selector sheet example page.

2024-02-06 17:45 UTC, andrespd99 requested changes

2024-02-06 17:45 UTC, andrespd99 commented on packages/avilatek_ui/lib/src/widgets/selector_sheet.dart
>    final Widget title;
Quita este parámetro y deja solo `appBar`

2024-02-06 17:45 UTC, andrespd99 commented on packages/avilatek_ui/lib/src/widgets/selector_sheet.dart
Muy bien! Solo un cambio:

No es necesario que le pases los items por parámetro. EL itemBuilder debería de ser de tipo `Widget Function(BuildContext, int)`, nota que el segundo parámetro del callback es un int, no widget, ese es el indice del item que se va a construir, pero eso ya queda del lado de la implementación.

Tambien podrías hacer algo similar al ListView, que tiene un constructor base, y un factory ListView.builder, de manera que puedas construir tu SelectorSheet con una lista de items (sin builder) o directamente con una función builder (itemBuilder) dinámicamente

2024-02-06 22:35 UTC, cadsvpt commented on packages/avilatek_ui/lib/src/widgets/selector_sheet.dart
>    final Widget title;
Listo!

2024-02-07 14:31 UTC, nathva approved these changes
Todo se ve bastante bien! Aprobado por mi parte. Te dejé un pequeño comentario, pero está asociado al ejemplo que implementaste más que al widget. 

Estaría muy cool poder implementar en el futuro, en otra versión, alguna opción que permita elegir más de un item, así como pasarle qué hacer en caso de que la lista que se le pasa esté vacía.

2024-02-07 14:31 UTC, nathva commented on example/lib/pages/selector_sheet/selector_sheet_example_page.dart
> +  final bool simulateInitialFetchingError;
Creo que no estás usando esta variable en ningún momento. Como no estás haciendo realmente un fetch sino que tienes la lista de items arriba (y por lo tanto no manejas status), considera quitar este parámetro!

2024-02-07 14:57 UTC, CADSV commented on packages/avilatek_ui/lib/src/widgets/selector_sheet.dart
>    final Widget title;
Listooo

2024-02-07 14:59 UTC, CADSV commented
> Todo se ve bastante bien! Aprobado por mi parte. Te dejé un pequeño comentario, pero está asociado al ejemplo que implementaste más que al widget.
> 
> Estaría muy cool poder implementar en el futuro, en otra versión, alguna opción que permita elegir más de un item, así como pasarle qué hacer en caso de que la lista que se le pasa esté vacía.

Siii pero Andrew y Luisao dijeron que eso sería otro widget

2024-02-07 15:01 UTC, CADSV commented on example/lib/pages/selector_sheet/selector_sheet_example_page.dart
> +  final bool simulateInitialFetchingError;
Coye jajajaj quizás eso fue copiando la estructura del example de otro widget, thanks!

2024-02-07 16:39 UTC, andrespd99 commented
> Todo se ve bastante bien! Aprobado por mi parte. Te dejé un pequeño comentario, pero está asociado al ejemplo que implementaste más que al widget.
> 
> Estaría muy cool poder implementar en el futuro, en otra versión, alguna opción que permita elegir más de un item, así como pasarle qué hacer en caso de que la lista que se le pasa esté vacía.

Podemos crear un feature request en los issues para tomarlo en una siguiente versión. Me gusta la idea

2024-02-15 17:12 UTC, andrespd99 approved these changes

2024-02-15 17:12 UTC, merged