feat: ✨ Pending Notifications bloc
Avila-Tek/flutter_common_lib pull request #9
Opened 2024-02-06 15:53 UTC by nathva

feat: ✨ Implemented abstract bloc for pending notifications. Developers can implement the bloc and pass the time interval in which they want to fetch the pending notifications, as well as any pending notification entity they wanna use.

2024-02-06 23:54 UTC, CADSV requested changes
Quedó brutal Nat! Y con la implementación del fetch bloc, se ve potente!
Los comentarios que te hice fueron mínimos para pulir, del resto congrats. Me guiaré de este bloc para el que me toca hacer en el sprint 3

2024-02-06 23:54 UTC, CADSV commented on packages/avilatek_bloc/lib/src/pending_notifications/pending_notifications_state.dart
`/// Returns `true` if the state is either [PendingNotificationsInitialFetching] or
  /// [PendingNotificationsRefetching].
  bool get isFetching =>
      // this is PendingNotificationsRefetching ||
      this is PendingNotificationsInitialFetching;`

Aquí sería mejor quitar la línea comentada de  `// this is PendingNotificationsRefetching ||` porque ya ese estado lo estarías manejando con el otro getter. Igual que sería bueno adaptar la docu de ese getter

2024-02-06 23:54 UTC, CADSV commented on packages/avilatek_bloc/lib/src/pending_notifications/pending_notifications_bloc.dart
Quitar este comentario `//  await subscription?.cancel();`

2024-02-15 14:52 UTC, lesanpi approved these changes

2024-02-15 17:26 UTC, andrespd99 approved these changes

2024-02-15 17:27 UTC, merged